package common

const (
  SUCCESS                   = "SUCCESS"
  ERROR                     = "ERROR"
  ERROR_INVALID_PARAMS      = "ERROR_INVALID_PARAMS"
  ERROR_AUTHENTICATION_FAIL = "ERROR_AUTHENTICATION_FAIL"
  
  ERROR_NOT_LOGGED          = "ERROR_NOT_LOGGED"
  ERROR_NOT_EXIST_USER      = "ERROR_NOT_EXIST_USER"
  ERROR_PASSWORD_FAIL       = "ERROR_PASSWORD_FAIL"

  ERROR_NOT_EXIST_ARTICLE   = "ERROR_NOT_EXIST_ARTICLE"
  ERROR_ADD_ARTICLE_FAIL    = "ERROR_ADD_ARTICLE_FAIL"
  ERROR_GET_ARTICLE_FAIL    = "ERROR_GET_ARTICLE_FAIL"
)
